name: Container - Playwright MCP
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
  push:
    branches: ["dev"]
    paths-ignore: ["examples/**"]

jobs:
  docker-ci:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.store_tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Get release image name
        id: image_name
        run: echo "image_name=$(make get-playwright-image-name)" >> $GITHUB_ENV
      - name: Get release image tag for Playwright MCP image
        id: image_tag
        run: echo "image_tag=$(make get-image-tag)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image With Tag
        id: builder
        run: |
          docker build --tag ${{ secrets.GCLOUD_REGISTRY}}/${{ secrets.GCLOUD_PROJECT_ID }}/${{ env.image_name }}:${{env.image_tag }} --file ./Dockerfile	.
        shell: bash
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCLOUD_SERVICE_KEY }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker ${{ secrets.GCLOUD_REGISTRY }}
        shell: bash
      - name: Push Docker Image to Google Cloud Registry
        run: |
          docker push ${{ secrets.GCLOUD_REGISTRY}}/${{ secrets.GCLOUD_PROJECT_ID }}/${{ env.image_name }}:${{env.image_tag }}
        shell: bash
      - name: Store tag as job output
        id: store_tag
        run: echo "image_tag=${{ env.image_tag }}" >> "$GITHUB_OUTPUT"

  manifest-ci:
    runs-on: ubuntu-latest
    needs: docker-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: kms-healthcare/il-ops
          token: ${{ secrets.PAT_TOKEN }}
      - name: Get an entry with a variable that might contain dots or spaces
        id: get_username
        uses: mikefarah/yq@v4.42.1
        with:
          cmd: yq e '.image.tag = "${{ needs.docker-ci.outputs.image-tag }}"' -i 'charts/playwright-mcp/values.prod.yaml'

      - name: Push changes to gitops
        run: |
          echo Pushing changes to kms-healthcare/il-ops
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit --allow-empty -m "Deploy \"${{ needs.docker-ci.outputs.image-tag }}\" tag into 'charts/playwright-mcp/values.prod.yaml'"
          git pull --rebase
          git push -u origin master
        shell: bash
